import esbuild from "esbuild";
import process from "process";
import fs from "fs";
import path from "path";
import { builtinModules } from "module";

// Node's built-in module names, plus their "node:" prefixed forms, so esbuild
// keeps them external (they must never be bundled into the plugin).
const builtins = [...builtinModules, ...builtinModules.map((m) => `node:${m}`)];

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// Output a complete, ready-to-install plugin folder: main.js next to the
// static plugin files Obsidian requires in the same directory.
const OUT_DIR = ".build";

fs.mkdirSync(OUT_DIR, { recursive: true });

/** Copy the static plugin files (manifest, styles) into the build folder. */
function copyStaticAssets() {
  for (const file of ["manifest.json", "styles.css"]) {
    if (fs.existsSync(file)) {
      fs.copyFileSync(file, path.join(OUT_DIR, file));
    }
  }
}

/** esbuild plugin: refresh static assets after each (re)build. */
const copyAssetsPlugin = {
  name: "copy-static-assets",
  setup(build) {
    build.onEnd(copyStaticAssets);
  },
};

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: path.join(OUT_DIR, "main.js"),
  minify: prod,
  plugins: [copyAssetsPlugin],
});

if (prod) {
  await context.rebuild();
  // Copy the static assets EXPLICITLY (and synchronously) here rather than
  // relying on the `onEnd` callback: `process.exit(0)` can fire before the
  // async `onEnd` hook runs, leaving `.build/` without manifest.json/styles.css
  // (and racily even without main.js). In CI that produced a release with no
  // installable assets. Copying here makes the production build deterministic.
  copyStaticAssets();
  await context.dispose();
} else {
  await context.watch();
}
